// <auto-generated />
namespace Student_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class intiload_studdent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intiload_studdent));
        
        string IMigrationMetadata.Id
        {
            get { return "202204041244435_intiload_studdent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
